-- =========================================================
-- Task Management System - Database Schema
-- Database: PostgreSQL
-- =========================================================


DROP TABLE IF EXISTS tasks;
DROP TABLE IF EXISTS users;


CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    email VARCHAR(255),
    role VARCHAR(255),
    created_at TIMESTAMP
);


CREATE TABLE tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255),
    description TEXT,
    status VARCHAR(255),
    priority VARCHAR(255),
    due_date DATE,
    created_at TIMESTAMP,
    user_id BIGINT,
    CONSTRAINT fk_tasks_user
        FOREIGN KEY (user_id)
        REFERENCES users(id)
);


INSERT INTO users (name, email, role, created_at)
VALUES
('Alice', 'alice@example.com', 'ADMIN', CURRENT_TIMESTAMP),
('Bob', 'bob@example.com', 'USER', CURRENT_TIMESTAMP);

INSERT INTO tasks (title, description, status, priority, due_date, created_at, user_id)
VALUES
('Finish assignment', 'Complete backend and frontend task management system', 'TODO', 'HIGH', CURRENT_DATE + INTERVAL '3 days', CURRENT_TIMESTAMP, 1),
('Fix UI layout', 'Adjust task list and user list layout', 'DOING', 'MEDIUM', CURRENT_DATE + INTERVAL '5 days', CURRENT_TIMESTAMP, 2),
('Deploy project', 'Deploy backend to Railway and frontend to Vercel', 'DONE', 'HIGH', CURRENT_DATE + INTERVAL '7 days', CURRENT_TIMESTAMP, 1);